# This project doesn't use rustfmt, these are only for hints with
#   rustfmt --check src/file.rs

doc_comment_code_block_width = 80
edition = "2021"
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 80
reorder_impl_items = true
style_edition = "2021"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
